### ISSUE TITLE
并不会进行每日任务是为什么

### ISSUE THREAD

**Issue by neeko8** [LinYuanovo/pikpak_auto_invite#10]
按照流程在GitHubActions中成功启用，但是发现在6.10分并不会自动执行，尝试修改cron表达式测试发现也并不会成功，是什么情况呢

**Comment by LinYuanovo** [comment]
抱歉，我的问题，因为GitHub Actions所采用的时区是UTC时区，比北京时间慢8个小时，所以实际上应该是早上10点运行

**Comment by neeko8** [comment]
原来如此
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LinYuanovo/pikpak_auto_invite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月26日(星期三) 晚上7:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LinYuanovo/pikpak_auto_invite] 并不会进行每日任务是为什么 (Issue #10)





 
抱歉，我的问题，因为GitHub Actions所采用的时区是UTC时区，比北京时间慢8个小时，所以实际上应该是早上10点运行

**Comment by neeko8** [comment]
刚刚将cron表达式改为20 11 * * *测试了一下，应该是北京时间19.20执行一次，但是好像还是没有执行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LinYuanovo/pikpak_auto_invite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月26日(星期三) 晚上7:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LinYuanovo/pikpak_auto_invite] 并不会进行每日任务是为什么 (Issue #10)





 
抱歉，我的问题，因为GitHub Actions所采用的时区是UTC时区，比北京时间慢8个小时，所以实际上应该是早上10点运行

**Comment by LinYuanovo** [comment]
有延迟的哦，有时候并不完全准时

**Comment by neeko8** [comment]
> 有麻烦的哦，有时候并不完全及时
我发现了！刚刚已经成功自动运行了，谢谢大佬解答
