### ISSUE TITLE
提示开启科学上网

### ISSUE THREAD

**Issue by zyancn** [LinYuanovo/pikpak_auto_invite#12]
Run python run.py
  python run.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/zyancn/pikpak_auto_invite/actions/runs/9682532634/job/26715770288#step:6:3).9.19/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.19/x6[4](https://github.com/zyancn/pikpak_auto_invite/actions/runs/9682532634/job/26715770288#step:6:4)/lib
    INVITE_CODE: ***
IP频繁,请更换IP或者稍后再试!!!
 Your operation is too frequent, please try again later
异常捕获:exceptions must derive from BaseException
请检查网络环境,(开启科学上网)重试!!!

**Comment by LinYuanovo** [comment]
操作频繁，请不要短时间内多次运行，按照教程运行成功后即可
