### ISSUE TITLE
python 用什么版本啊

### ISSUE THREAD

**Issue by perl9** [LinYuanovo/pikpak_auto_invite#2]

**Comment by k0baya** [comment]
实测3.10可用，嫌麻烦可以直接使用我打包好的docker镜像，已经把邀请码、代理都变量化，并添加定时执行。
[k0baya/pikpak_auto_invite/docker-compose.yaml](https://github.com/k0baya/pikpak_auto_invite/blob/main/docker-compose.yaml)
