### ISSUE TITLE
是因为没有PUSHPLUS_TOKEN环境变量报错吗？

### ISSUE THREAD

**Issue by pipi0216** [LinYuanovo/pikpak_auto_invite#22]
请输入邀请码: 15151
请按照文档设置PUSHPLUS_TOKEN环境变量
=========正在邀请第 1 个邀请码=========
异常捕获:0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.internal.temp-mail.io/api/v3/email/new')
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DE1B7B49D0>
Traceback (most recent call last):
  File "D:\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Python\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "D:\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

进程已结束，退出代码为 0

**Comment by zbumian** [comment]
`Run python run.py
  python run.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/zbumian/pikpak_auto_invite/actions/runs/9716791789/job/26821151784#step:6:3).9.19/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.19/x6[4](https://github.com/zbumian/pikpak_auto_invite/actions/runs/9716791789/job/26821151784#step:6:4)/lib
    INVITE_CODE: ***
    PUSHPLUS_TOKEN: ***
=========正在邀请第 1 个邀请码=========
异常捕获:0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.internal.temp-mail.io/api/v3/email/new')
推送成功

是不是临时邮箱用不了了`

**Comment by misss666666** [comment]
用不了了，跟楼下的问题一样，楼主怎么解决？

**Comment by pipi0216** [comment]
action可以，Python本地运行好像不行

**Comment by misss666666** [comment]
大佬如何再重新创一个新的脚本，该怎么创建？  如果账号被封了，如何修改邀请码更换新的账号？

**Comment by misss666666** [comment]
最近官方在抓这个动不动就被封，  越来越严格了。 感觉好像是人工审核的兄弟们。

**Comment by misss666666** [comment]
此工作流程已被手动禁用。怎么解？

**Comment by LinYuanovo** [comment]
已恢复正常，昨晚临时邮箱崩了

**Comment by LinYuanovo** [comment]
> 大佬如何再重新创一个新的脚本，该怎么创建？ 如果账号被封了，如何修改邀请码更换新的账号？

直接修改变量INVITE_CODE即可
