### ISSUE TITLE
滑块验证失败，求帮助

### ISSUE THREAD

**Issue by fallpavilion** [LinYuanovo/pikpak_auto_invite#29]
![image](https://github.com/LinYuanovo/pikpak_auto_invite/assets/73598810/cf5703b4-95c6-4985-aeaa-2725ef5f03b8)

**Comment by lingdanqing** [comment]
接口稍微加强了一点

**Comment by LinYuanovo** [comment]
滑块加强了，等待修复吧

**Comment by thisThink** [comment]
第一天使用，遇到这了。还没体验就要结束了吗

**Comment by LinYuanovo** [comment]
已修复
