### ISSUE TITLE
求助如何设置代理

### ISSUE THREAD

**Issue by bargaindr** [LinYuanovo/pikpak_auto_invite#30]
如何给自己使用的魔法提取代理添加

**Comment by LinYuanovo** [comment]
clash与v2ray等代理工具同理，代理只在你本地运行时有效，除非你有公网，这里有一篇文章：[v2ray 下 windows terminal 代理的配置](https://lynxux.github.io/posts/2021-07-01-windows-terminal-proxy/)
![image](https://github.com/LinYuanovo/pikpak_auto_invite/assets/74068830/574262b7-be89-4bb6-8922-d2fa581a1fd3)
例如我的clash这里的端口是7890
所以放在脚本里就是PROXY = 'http://127.0.0.1:7890'，这时候脚本的请求就会通过你的科学上网
