### ISSUE TITLE
d参数获取，低调使用

### ISSUE THREAD

**Issue by lingdanqing** [LinYuanovo/pikpak_auto_invite#32]
"""
by lingdanqing
"""

def get_d(input_str):
    def rotate_left(value, shift):
        return ((value << shift) | (value >> (32 - shift))) & 0xFFFFFFFF

    def multiply_and_combine(x, y):
        x_high = (x >> 16) & 0xFFFF
        x_low = x & 0xFFFF
        y_high = (y >> 16) & 0xFFFF
        y_low = y & 0xFFFF
        return ((x_high * y_low + x_low * y_high) << 16) + (x_low * y_low) & 0xFFFFFFFF

    c = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a]

    for i in range(len(input_str)):
        c[i % 4] = (c[i % 4] ^ multiply_and_combine(ord(input_str[i]), 0x9e3779b9)) & 0xFFFFFFFF
        c[i % 4] = rotate_left(c[i % 4], 13)

    for _ in range(8):
        for j in range(4):
            c[j] = (c[j] + multiply_and_combine(c[(j + 1) % 4], 0x85ebca6b)) & 0xFFFFFFFF
            c[j] = rotate_left(c[j], 17)
            c[j] = (c[j] ^ c[(j + 2) % 4]) & 0xFFFFFFFF

    result = c[0] ^ c[1] ^ c[2] ^ c[3]
    result = multiply_and_combine(result, 0xc2b2ae35)
    result = (result ^ (result >> 16)) & 0xFFFFFFFF
    return format(result, '08x')

# inp_d = f"{pid}{xid}{f}"
# d_data = get_d(inp_d)

**Comment by LinYuanovo** [comment]
不建议公开兄弟，不然改的太快了

**Comment by LinYuanovo** [comment]
我删除了哈
