### ISSUE TITLE
滑块验证好像一直过不了

### ISSUE THREAD

**Issue by yuci991111** [LinYuanovo/pikpak_auto_invite#40]
`验证滑块中...
删除缓存图片成功
验证失败, 重新验证滑块中...
验证滑块中...
删除缓存图片成功
验证失败, 重新验证滑块中...
验证滑块中...
删除缓存图片成功
异常捕获:int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by sometimee** [comment]
我今天也出现滑块验证过不了的情况

**Comment by LinYuanovo** [comment]
有问题先更新，更新了了还有问题再提issue
